-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Osallistuminen CASCADE;
DROP TABLE IF EXISTS Elainkoe CASCADE;
DROP TABLE IF EXISTS Elainkoelupa CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;

DROP TYPE IF EXISTS kayttajanoikeudet;
DROP TYPE IF EXISTS elainlaji;
